export interface IndicatorParams {
  // 主图
  maPeriods: number[]
  /** 主图叠加：主指标为 MA 时同时绘制 EMA 线（复合均线系统） */
  maOverlayEma: boolean
  bollPeriod: number
  bollMult: number
  sarAfStart: number
  sarAfStep: number
  sarAfMax: number
  ichimokuTenkan: number
  ichimokuKijun: number
  ichimokuSpanB: number
  ichimokuDisplacement: number
  // 副图
  macdFast: number
  macdSlow: number
  macdSignal: number
  kdjN: number
  kdjM1: number
  kdjM2: number
  rsiPeriod: number
  wrPeriod: number
  obvMaPeriod: number
  atrPeriod: number
  dmiPeriod: number
  cciPeriod: number
  psyPeriod: number
  stochK: number
  stochSmooth: number
  stochD: number
  rocPeriod: number
  momPeriod: number
  bbwPeriod: number
  bbwMult: number
  stPeriod: number
  stMult: number
  mfiPeriod: number
  aoFast: number
  aoSlow: number
  cmfPeriod: number
  donchianPeriod: number
  aroonPeriod: number
  volMaPeriod: number
  trixPeriod: number
  dpoPeriod: number
}

export const DEFAULT_INDICATOR_PARAMS: IndicatorParams = {
  // 主图
  maPeriods: [5, 10, 20],
  maOverlayEma: false,
  bollPeriod: 20,
  bollMult: 2,
  sarAfStart: 0.02,
  sarAfStep: 0.02,
  sarAfMax: 0.2,
  ichimokuTenkan: 9,
  ichimokuKijun: 26,
  ichimokuSpanB: 52,
  ichimokuDisplacement: 26,
  // 副图
  macdFast: 12,
  macdSlow: 26,
  macdSignal: 9,
  kdjN: 9,
  kdjM1: 3,
  kdjM2: 3,
  rsiPeriod: 14,
  wrPeriod: 14,
  obvMaPeriod: 1, // 1 = 原始 OBV 不平滑；>1 时按 SMA 平滑
  atrPeriod: 14,
  dmiPeriod: 14,
  cciPeriod: 20,
  psyPeriod: 12,
  stochK: 14,
  stochSmooth: 3,
  stochD: 3,
  rocPeriod: 12,
  momPeriod: 10,
  bbwPeriod: 20,
  bbwMult: 2,
  stPeriod: 10,
  stMult: 3,
  mfiPeriod: 14,
  aoFast: 5,
  aoSlow: 34,
  cmfPeriod: 20,
  donchianPeriod: 20,
  aroonPeriod: 25,
  volMaPeriod: 5,
  trixPeriod: 15,
  dpoPeriod: 20,
}
